version: '0.1.{build}'
image: Visual Studio 2017
environment:
    dotnet_version: "2.1.300"
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    nodejs_version: "8"
install:
- ps: Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile ".\install.ps1"
- ps: '& .\install.ps1 -version "$env:dotnet_version" -InstallDir ".\.dotnet"'
- ps: Install-Product node $env:nodejs_version

build_script:
- dotnet publish --output ..\..\artifacts\approot src\HelloCoreClrApp
- dotnet msbuild /t:publish /p:output=..\artifacts\wwwroot ui

before_test:
- pushd ui && npm install karma-appveyor-reporter && popd

test_script:
- dotnet test test\HelloCoreClrApp.Test\HelloCoreClrApp.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutputDirectory=..\..\reports
- npm run lint --prefix ui
- npm run unit-tests --prefix ui -- --reporters dots,coverage-istanbul,appveyor
- npm run e2e-tests:prepare --prefix ui
- npm run e2e-tests --prefix ui

after_test:
- npm install codecov
- node_modules\.bin\codecov --disable=gcov -f reports\coverage.xml
- node_modules\.bin\codecov --disable=gcov -f reports\coverage-ts.json

cache:
- '%USERPROFILE%\.nuget\packages -> appveyor.yml'
- 'ui\node_modules -> appveyor.yml'
- 'node_modules -> appveyor.yml'
